### PR TITLE
feat: implementing dynamic device allocation.

### PR DESCRIPTION
**Pull request by drugilsberg**
👋 
I prepared this PR to adapt tensor instantiation and artifact loading to dynamically use CPU when GPU is not available.

Thought it could be a useful addition and happy to iterate in case the style or the code need some further changes.

Signed-off-by: Matteo Manica <drugilsberg@gmail.com>

### CODE REVIEW

**Comment by drugilsberg** [comment]
Hey @GuoJeff, tagging you only because you were the author of the last commit :).
Is there any interest in this PR? Otherwise I think we can safely close it.

**Comment by johnberroa** [comment]
Hi @drugilsberg, I also ran into this cuda problem when trying to run the codebase on a non-cuda device. I think the changes are definitely needed!

**Comment by drugilsberg** [comment]
> Hi @drugilsberg, I also ran into this cuda problem when trying to run the codebase on a non-cuda device. I think the changes are definitely needed!

Feel free to use the fork we created in case of need: https://github.com/GT4SD/reinvent-models/tree/dynamic-device-handling

**Comment by drugilsberg** [comment]
Closing after the conversation on https://github.com/MolecularAI/Reinvent/issues/41

**Pull request closed without merging**
